services:
  # Banco de Dados.
  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=agendamento_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Back-End.
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=agendamento_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
      
  # Front-End
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      # Esse volume anônimo impede que o Docker tente sobrescrever 
      # a pasta node_modules de dentro do container com a do seu PC
      - /app/node_modules
    depends_on:
      - web # Substitua 'web' pelo nome exato que você deu ao serviço do Django

volumes:
  postgres_data: