# Generated by Django 5.0.14 on 2026-08-27 03:04

from django.db import migrations

def criar_dias_da_semana(apps, schema_editor):
    DiaSemana = apps.get_model('agendamentos', 'DiaSemana')
    
    # Cria os 7 dias da semana no banco caso eles nao existam.
    for i in range(7):
        DiaSemana.objects.get_or_create(dia=i)

def reverter_dias_da_semana(apps, schema_editor):
    DiaSemana = apps.get_model('agendamentos', 'DiaSemana')
    DiaSemana.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(criar_dias_da_semana, reverter_dias_da_semana),
    ]
